name: Auto Label New Issues

on:
  issues:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add "Needs Triage" label to new issue
        uses: actions/github-script@v5
        with:
          node-version: '20'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, issue } = context.payload;
            const issueNumber = issue.number;

            const octokit = context.octokit;

            octokit.rest.issues.addLabels({
              owner,
              repo,
              issue_number: issueNumber,
              labels: ['needs triage']
            });

