name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add "Needs Triage" label to new/reopened issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.payload.issue.number;

            const labelsToAdd = ['triage'];

            await github.issues.addLabels({
              owner,
              repo,
              issue_number: issueNumber,
              labels: labelsToAdd
            });
